#!/usr/bin/env python3
"""Build the bounded RN7 paid-need recalibration run without production artifacts."""
from __future__ import annotations

import json
from pathlib import Path

from abvx_harness.book_radar import assess_portfolio_similarity
from abvx_harness.book_radar_discovery import validate_buyer_situation


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "book-radar" / "runs" / "rn7-paid-need"
DATE = "2026-09-08"


def dump(name, value):
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / name).write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n")


SOURCES = [
    {"id":"EPA-SEPTIC","publisher":"U.S. Environmental Protection Agency","url":"https://www.epa.gov/septic/new-homebuyers-brochure-and-guide-septic-systems","checked_at":DATE,"observation":"Current free homebuyer guide explains septic systems and recommends pre-purchase inspection.","interpretation":"Problem exists; a general buyer guide is already free.","limitations":"Does not measure book purchases."},
    {"id":"AMZ-SEPTIC","publisher":"Amazon.com","url":"https://www.amazon.com/s?k=septic+inspection+home+buyer+guide&i=stripbooks","checked_at":DATE,"observation":"A direct 2026 Kindle title, Septic System Risk for Homebuyers (ASIN B0GRBXQFN7), promises inspection interpretation and risk framing.","interpretation":"The proposed advantage is already claimed by a current entrant.","limitations":"Visibility, reviews and rank were insufficient for a sales estimate."},
    {"id":"NRVIA-COST","publisher":"National RV Inspectors Association","url":"https://nrvia.org/2023/08/brad-siedschlag-found-inspecting-rvs-to-be-a-portal-to-a-better-life/","checked_at":DATE,"observation":"Published inspector examples quote roughly $740–$1,500 depending on vehicle, excluding add-ons.","interpretation":"RV buyers visibly spend on inspection and receive detailed reports.","limitations":"Association profile of one inspector; not a market average."},
    {"id":"NRVIA-BUYER","publisher":"National RV Inspectors Association","url":"https://nrvia.org/what-you-need-to-know/","checked_at":DATE,"observation":"Buyer guidance says to request scope, sample report and points of inspection.","interpretation":"There is a concrete pre-purchase information job.","limitations":"Provider association has an incentive to promote inspections."},
    {"id":"AMZ-RV","publisher":"Amazon.com","url":"https://www.amazon.com/s?k=RV+inspection+report+buyer+guide&i=stripbooks","checked_at":DATE,"observation":"371 results; visible direct/near-direct books include two June 2026 buyer guides at about EUR12–15, a 2020 inspection title with 15 ratings, and older buyer guides with 50–71 ratings.","interpretation":"Book format is established but the accessible advantage is weak.","limitations":"Query count is noisy; ratings and prices are observations, not unit estimates."},
    {"id":"CAI-RESERVE","publisher":"Community Associations Institute","url":"https://www.caionline.org/advocacy/public-policies/reserve-study-and-funding/","checked_at":DATE,"observation":"Reserve studies combine physical and financial analysis and can affect special assessments; CAI supports disclosure to buyers.","interpretation":"A consequential buyer document and problem exist.","limitations":"Policy statement, not consumer purchase data; rules vary by state."},
    {"id":"AMZ-HOA","publisher":"Amazon.com","url":"https://www.amazon.com/s?k=HOA+reserve+study+buyer+guide&i=stripbooks","checked_at":DATE,"observation":"Five exact results, including direct buyer-due-diligence products published Aug 12, Aug 25, Sep 5, Sep 6 and Sep 7, 2026; visible prices roughly EUR11–19 and one title had 2 ratings.","interpretation":"The exact shelf filled rapidly; no distinct accessible advantage remains in the tested thesis.","limitations":"Very new titles have little traction history."},
    {"id":"FSA-OFFERS","publisher":"U.S. Department of Education, Federal Student Aid","url":"https://studentaid.gov/articles/evaluating-financial-aid-offers/","checked_at":DATE,"observation":"Official current guidance explains comparison of non-standardized aid offers and costs.","interpretation":"Problem and decision deadline are real.","limitations":"Does not establish paid book demand."},
    {"id":"NICHE-DECODER","publisher":"Niche","url":"https://www.niche.com/about/niche-launches-college-financial-aid-comparison-tool-to-help-families-decode-and-compare-offers/","checked_at":DATE,"observation":"A free upload-based financial-aid decoder launched in March 2026.","interpretation":"A proposed normalization workbook faces a stronger free substitute.","limitations":"Vendor announcement; adoption not disclosed."},
    {"id":"AAEP-PPE","publisher":"American Association of Equine Practitioners","url":"https://aaep.org/resource/dont-skip-the-purchase-exam/","checked_at":DATE,"observation":"AAEP advises buyers to invest in a customized purchase exam and communicate intended use to the veterinarian.","interpretation":"Problem and professional spending are established.","limitations":"No price or book-demand evidence."},
    {"id":"AAEP-REPORT","publisher":"American Association of Equine Practitioners","url":"https://aaep.org/resource/guidelines-for-reporting-purchase-examinations/","checked_at":DATE,"observation":"Reporting guidance makes the veterinarian responsible for exam scope while suitability remains the buyer's decision.","interpretation":"A buyer aid would require careful veterinary boundaries and expert review.","limitations":"Professional guidance, not a buyer product study."},
    {"id":"DOE-AUDIT","publisher":"U.S. Department of Energy","url":"https://www.energy.gov/sites/prod/files/guide_to_home_energy_assessments.pdf","checked_at":DATE,"observation":"A professional assessment is intended to identify cost-effective energy improvements.","interpretation":"Homeowners buy an assessment to prioritize spending.","limitations":"Older guide and no current service-price data."},
    {"id":"AMZ-ENERGY","publisher":"Amazon.com","url":"https://www.amazon.com/s?k=home+energy+audit+report+guide&i=stripbooks","checked_at":DATE,"observation":"16 results; visible books focus on DIY audits, energy efficiency or professional training. A 2024 DIY guide was about EUR10.75; a 2023 title had 13 ratings; a June 2026 playbook had no visible rating.","interpretation":"Adjacent book buying exists, but demand for post-audit report-to-action workflow is unproved.","limitations":"No BSR history and query matching is imperfect."},
    {"id":"AARP-HIRE","publisher":"AARP","url":"https://www.aarp.org/caregiving/financial-legal/who-to-hire-caregiving-support/","checked_at":DATE,"observation":"AARP reports one-third of family caregivers use paid help and explains agency versus direct-hire trade-offs.","interpretation":"Families visibly pay and face a consequential vendor-selection job.","limitations":"The cited share comes from AARP/NAC research; it does not measure book demand."},
    {"id":"AARP-CHECKLIST","publisher":"AARP","url":"https://www.aarp.org/caregiving/home-care/hiring-caregiver/","checked_at":DATE,"observation":"Free guidance and a contract-question checklist already exist.","interpretation":"A paid product must normalize actual agency proposals and answers, not repeat generic questions.","limitations":"Free alternative quality not tested with buyers."},
    {"id":"AMZ-CARE","publisher":"Amazon.com","url":"https://www.amazon.com/s?k=hire+in-home+caregiver+comparison+workbook&i=stripbooks","checked_at":DATE,"observation":"Exact query returned one direct 1995 family guide with 1 rating. Adjacent paid caregiving formats include a 2024 toolkit with 162 ratings and current paperback logs around EUR7–10.","interpretation":"Book-format spending exists adjacent to a weak exact shelf; proposal comparison is not visibly served.","limitations":"Search placement and ratings do not establish conversion for the proposed product."},
    {"id":"ISA-REPORTS","publisher":"International Society of Arboriculture","url":"https://www.isa-arbor.com/Online-Learning/More-Resources/Sample-Reports","checked_at":DATE,"observation":"ISA publishes multiple professional sample tree-risk reports.","interpretation":"Homeowners can receive structured reports but interpretation is safety-sensitive.","limitations":"No consumer spending or book-demand measure."},
    {"id":"FRESNO-FOOD","publisher":"County of Fresno","url":"https://www.fresnocountyca.gov/Departments/Public-Health/Environmental-Health/Consumer-Food-Program/Mobile-Food-Vendors/Fresno-County-Mobile-Food-Vendor-Permit-Inspection-Checklist","checked_at":DATE,"observation":"Mobile food vendors must obtain a permit and pass local vehicle inspection before opening.","interpretation":"Trigger and deadline are strong.","limitations":"County-specific rules make a national book volatile."},
    {"id":"AARP-WORKBOOK","publisher":"AARP","url":"https://employerportal.aarp.org/resource/financial-workbook-for-family-caregivers/","checked_at":DATE,"observation":"AARP provides a free caregiver financial workbook and reports substantial caregiver out-of-pocket spending.","interpretation":"General caregiver organization is well supplied for free; agency-proposal comparison must be narrower.","limitations":"Out-of-pocket care spending is not publishing spend."},
    {"id":"ABYC-SURVEY","publisher":"American Boat & Yacht Council","url":"https://abycinc.org/recreational-boaters/surveying-a-boat/","checked_at":DATE,"observation":"ABYC says a prepurchase survey produces a technical written report for purchase decisions, negotiation, insurance and lending; buyers should ask the surveyor to explain unclear findings.","interpretation":"The buyer job and professional spend are real, but safety and technical interpretation belong to qualified professionals.","limitations":"No book-demand or survey-price evidence."},
    {"id":"ASV-RECORDS","publisher":"Association of Shelter Veterinarians","url":"https://www.sheltervet.org/assets/docs/6__Medical_Health_Final_07AUG2024.pdf","checked_at":DATE,"observation":"Shelter standards call for accurate dated medical records covering findings, tests, procedures and treatments.","interpretation":"A record-handoff job exists, but buyer dissatisfaction and publishing spend were not established.","limitations":"Professional shelter standard, not consumer demand evidence."},
    {"id":"CCI-CONDITION","publisher":"Canadian Conservation Institute","url":"https://www.canada.ca/en/conservation-institute/services/conservation-preservation-publications/canadian-conservation-institute-notes/condition-reporting-paintings-examination-techniques.html","checked_at":DATE,"observation":"Official conservation guidance provides a detailed condition-report checklist and specialist terminology.","interpretation":"Condition reporting is a real structured job; safe interpretation remains specialist work.","limitations":"No consumer spending or book-demand evidence."},
    {"id":"RAM-DUE-DILIGENCE","publisher":"Responsible Art Market","url":"https://www.responsibleartmarket.org/guidelines/art-transaction-due-diligence-toolkit/toolkit/","checked_at":DATE,"observation":"The toolkit recommends an independent specialist conservator and treats condition reports as important transaction documents.","interpretation":"A consequential art-purchase job exists but creates specialist dependency.","limitations":"Industry guidance, not publishing demand evidence."}
]


def dims(problem, spend, book, gap, reach, delivery, ids):
    values = [problem, spend, book, gap, reach, delivery]
    keys = ["problem_evidence","spending_evidence","book_format_demand","competitive_gap","reachability","delivery_fit"]
    return {k:{"status":v,"source_ids":ids.get(k,[])} for k,v in zip(keys,values)}


def situation(i, name, buyer, payer, trigger, job, deadline, current, spend, unmet, fit, channel, evidence, decision, reason, origin):
    item={"id":f"RN7R-{i:03d}","name":name,"buyer":buyer,"payer":payer,"purchase_trigger":trigger,"job_to_be_done":job,"deadline":deadline,"current_solution":current,"current_spend":spend,"unmet_need":unmet,"publishing_format_fit":fit,"discovery_channel":channel,"discovery_origin":origin,"evidence_dimensions":evidence,"decision_state":decision,"decision_reason":reason}
    validate_buyer_situation(item)
    return item


def main():
    s=[]
    s.append(situation(1,"RV inspection report decision companion","Used RV buyer","Buyer","Independent inspection report arrives before contingency expires","Separate costly findings, questions and negotiation items without replacing an inspector","Days","Inspector call, forums, notes","Professional inspection commonly hundreds to over $1,000","Long photo-rich report is hard to turn into a bounded action list","Paperback worksheet is plausible","Amazon and RV-inspection search",dims("SUPPORTED","SUPPORTED","SUPPORTED","NEGATIVE","SUPPORTED","SUPPORTED",{"problem_evidence":["NRVIA-BUYER"],"spending_evidence":["NRVIA-COST"],"book_format_demand":["AMZ-RV"],"competitive_gap":["AMZ-RV"],"reachability":["AMZ-RV"],"delivery_fit":["NRVIA-BUYER"]}),"REJECTED_ON_EVIDENCE","Direct and near-direct books already cover inspection, deal breakers and buying decisions; no defensible accessible advantage was found.","BOOKS_AND_MATERIALS"))
    s.append(situation(2,"HOA reserve-study buyer packet","Condo/HOA homebuyer","Buyer","Disclosure packet arrives before closing","Identify reserve, assessment and document questions","Days","Agent, attorney, online articles","Legal/inspection services and consequential property purchase","Reserve and meeting documents are hard to connect","Paperback packet is plausible","Amazon and HOA buyer search",dims("SUPPORTED","SUPPORTED","SUPPORTED","NEGATIVE","SUPPORTED","SUPPORTED",{"problem_evidence":["CAI-RESERVE"],"spending_evidence":["CAI-RESERVE"],"book_format_demand":["AMZ-HOA"],"competitive_gap":["AMZ-HOA"],"reachability":["AMZ-HOA"],"delivery_fit":["CAI-RESERVE"]}),"REJECTED_ON_EVIDENCE","Five very recent exact books now claim the same due-diligence job; a narrower advantage was not evidenced.","BOOKS_AND_MATERIALS"))
    s.append(situation(3,"Septic inspection report decoder","Homebuyer buying a septic property","Buyer","Inspection report arrives before commitment","Extract findings, missing tests and professional questions","Days","EPA guide, inspector, agent","Inspection and possible repair/replacement","Generic guides do not necessarily structure the buyer's report","Paperback worksheet is plausible","Amazon and homebuyer search",dims("SUPPORTED","SUPPORTED","SUPPORTED","NEGATIVE","SUPPORTED","SUPPORTED",{"problem_evidence":["EPA-SEPTIC"],"spending_evidence":["EPA-SEPTIC"],"book_format_demand":["AMZ-SEPTIC"],"competitive_gap":["AMZ-SEPTIC","EPA-SEPTIC"],"reachability":["AMZ-SEPTIC"],"delivery_fit":["EPA-SEPTIC"]}),"REJECTED_ON_EVIDENCE","A current direct entrant already promises inspection interpretation and risk framing alongside a strong free official guide.","BOOKS_AND_MATERIALS"))
    s.append(situation(4,"Financial-aid offer normalizer","Student and parent choosing a U.S. college","Family","Aid offers arrive before enrollment deadline","Compare net cost, gift aid, work study and debt","Weeks","Official worksheet, free upload tools, spreadsheets","Tuition and education financing","Offers use inconsistent structures","Workbook is technically suitable","Search and school counseling",dims("SUPPORTED","SUPPORTED","NEGATIVE","NEGATIVE","SUPPORTED","SUPPORTED",{"problem_evidence":["FSA-OFFERS"],"spending_evidence":["FSA-OFFERS"],"book_format_demand":["NICHE-DECODER"],"competitive_gap":["NICHE-DECODER","FSA-OFFERS"],"reachability":["FSA-OFFERS"],"delivery_fit":["FSA-OFFERS"]}),"REJECTED_ON_EVIDENCE","Free official and upload-based normalization tools beat a static workbook on the same outcome.","SERVICE_OR_TRAINING_SPEND"))
    s.append(situation(5,"Horse PPE question and decision record","First-time horse buyer","Buyer","Veterinarian schedules or delivers a purchase exam","Define intended use, preserve findings and ask the veterinarian precise questions","Days","Trainer and veterinarian discussion","Customized veterinary purchase examination","Emotional purchase and non-binary findings are difficult to document","Guided workbook could help","Equestrian search and tack channels",dims("SUPPORTED","SUPPORTED","UNKNOWN","SUPPORTED","SUPPORTED","NEGATIVE",{"problem_evidence":["AAEP-PPE","AAEP-REPORT"],"spending_evidence":["AAEP-PPE"],"competitive_gap":["AAEP-REPORT"],"reachability":["AAEP-PPE"],"delivery_fit":["AAEP-REPORT"]}),"ATTRACTIVE_BUT_NOT_FOR_US","Credible sequencing and safe boundaries require equine-veterinary expertise outside the autonomous production model.","SERVICE_OR_TRAINING_SPEND"))
    s.append(situation(6,"Home energy-audit action sorter","Homeowner who bought an energy audit","Homeowner","Professional audit report arrives before retrofit quotes","Convert recommendations into assumptions, quote requests and staged decisions","Weeks","Auditor call, contractor quotes, spreadsheet","Assessment and later retrofit work","Reports and contractor proposals are difficult to compare","Reusable reference plus write-in packet","Amazon and energy-audit search",dims("SUPPORTED","SUPPORTED","SUPPORTED","UNKNOWN","SUPPORTED","SUPPORTED",{"problem_evidence":["DOE-AUDIT"],"spending_evidence":["DOE-AUDIT"],"book_format_demand":["AMZ-ENERGY"],"competitive_gap":[],"reachability":["AMZ-ENERGY"],"delivery_fit":["DOE-AUDIT"]}),"INSUFFICIENT_EVIDENCE","Adjacent books exist, but no reliable evidence yet shows buyers will purchase a post-audit report-to-action system.","BOOKS_AND_MATERIALS"))
    s.append(situation(7,"Tree-risk report question companion","Homeowner receiving an arborist report","Homeowner","Risk report arrives after a tree concern or insurer request","Understand stated limitations and prepare follow-up questions","Days","Arborist call and online search","Professional arborist assessment","Risk categories and limitations can be misunderstood","Short reference is possible","Search after report receipt",dims("SUPPORTED","UNKNOWN","UNKNOWN","UNKNOWN","SUPPORTED","NEGATIVE",{"problem_evidence":["ISA-REPORTS"],"reachability":["ISA-REPORTS"],"delivery_fit":["ISA-REPORTS"]}),"ATTRACTIVE_BUT_NOT_FOR_US","Safety consequences and specialist interpretation create unacceptable expert dependency.","UNMET_NEED"))
    s.append(situation(8,"Food-truck pre-opening inspection binder","First-time mobile food vendor","Owner","Local pre-operational inspection is scheduled","Map local requirements to evidence and open items","Days","County checklist and consultant","Vehicle buildout, permits and consulting","Requirements are scattered across agencies","Local binder could fit","County search",dims("SUPPORTED","SUPPORTED","UNKNOWN","UNKNOWN","SUPPORTED","NEGATIVE",{"problem_evidence":["FRESNO-FOOD"],"spending_evidence":["FRESNO-FOOD"],"reachability":["FRESNO-FOOD"],"delivery_fit":["FRESNO-FOOD"]}),"ATTRACTIVE_BUT_NOT_FOR_US","County variation and update burden exceed the fast autonomous publishing boundary.","SERVICE_OR_TRAINING_SPEND"))
    s.append(situation(9,"In-home caregiver agency proposal comparator","Family member arranging paid home care","Family","Two or more agency assessments or proposals arrive","Normalize scope, minimum hours, backup coverage, supervision, exclusions and written answers","Days","Calls, AARP checklist, personal notes","Paid home-care services","Generic checklists do not preserve proposal differences and answers","Reference plus write-in comparison packet","Amazon, caregiving search and employer caregiver programs",dims("SUPPORTED","SUPPORTED","SUPPORTED","SUPPORTED","SUPPORTED","SUPPORTED",{"problem_evidence":["AARP-HIRE","AARP-CHECKLIST"],"spending_evidence":["AARP-HIRE","AARP-WORKBOOK"],"book_format_demand":["AMZ-CARE"],"competitive_gap":["AMZ-CARE","AARP-CHECKLIST"],"reachability":["AMZ-CARE","AARP-HIRE"],"delivery_fit":["AARP-CHECKLIST"]}),"READY_FOR_VALIDATION","Independent evidence supports the paid decision and adjacent book use; the untested assumption is willingness to buy this narrower comparison packet.","SERVICE_OR_TRAINING_SPEND"))
    s.append(situation(10,"Marine survey report follow-up pack","Used recreational boat buyer","Buyer","Condition-and-value survey arrives before closing/insurance","Separate findings, limitations and specialist questions","Days","Surveyor and broker calls","Professional marine survey","Long reports mix safety, valuation and maintenance","Paperback packet plausible","Boat-buyer search",dims("SUPPORTED","SUPPORTED","UNKNOWN","UNKNOWN","SUPPORTED","NEGATIVE",{"problem_evidence":["ABYC-SURVEY"],"spending_evidence":["ABYC-SURVEY"],"reachability":["ABYC-SURVEY"],"delivery_fit":["ABYC-SURVEY"]}),"ATTRACTIVE_BUT_NOT_FOR_US","Marine safety and survey interpretation require expertise not established here.","SERVICE_OR_TRAINING_SPEND"))
    s.append(situation(11,"Rescue-dog medical record organizer","New adopter of a dog with fragmented records","Adopter","Shelter and veterinary records arrive around adoption","Create a clean questions-and-record handoff for the new veterinarian","Weeks","Folder, clinic portal, notes","Veterinary visit and insurance","Records may use different names and omit history","Write-in organizer plausible","Pet adoption and Amazon search",dims("SUPPORTED","UNKNOWN","UNKNOWN","UNKNOWN","UNKNOWN","UNKNOWN",{"problem_evidence":["ASV-RECORDS"]}),"INSUFFICIENT_EVIDENCE","The record job exists, but consumer dissatisfaction, spending and book-format demand were not independently established in this bounded pass.","UNMET_NEED"))
    s.append(situation(12,"Art condition-report handoff book","New small collector buying a work with a condition report","Collector","Condition report arrives before purchase or transport","Preserve condition facts and questions for seller, insurer or conservator","Days","Dealer explanation and personal notes","Appraisal, insurance or conservation services","Specialist language and photographic condition changes are hard to track","Archival workbook plausible","Collector and conservation search",dims("SUPPORTED","UNKNOWN","UNKNOWN","UNKNOWN","UNKNOWN","NEGATIVE",{"problem_evidence":["CCI-CONDITION","RAM-DUE-DILIGENCE"],"delivery_fit":["RAM-DUE-DILIGENCE"]}),"ATTRACTIVE_BUT_NOT_FOR_US","Credible condition interpretation and image standards require specialist editorial judgment.","UNMET_NEED"))

    deep_ids={"RN7R-001","RN7R-002","RN7R-003","RN7R-006","RN7R-009"}
    deep=[x for x in s if x["id"] in deep_ids]
    hypotheses=[
      {"opportunity_id":"RN7R-009","status":"READY_FOR_VALIDATION","buyer_and_moment":"Adult child or spouse comparing home-care agencies after receiving proposals.","promised_result":"A traceable apples-to-apples record of scope, scheduling, backup coverage, supervision, exclusions, price structure and unanswered questions.","content_and_format":"US-focused 7.5x9.25 paperback reference plus write-in comparison packet; no medical, employment-law or care-plan advice.","price_hypothesis":{"value_usd":14.99,"confidence":"LOW","basis":"Adjacent current caregiver paperbacks are visibly sold around EUR7–10 and the direct old guide has no usable price; test $14.99 as a consequential-decision workbook anchor, not a final price."},"paid_alternatives":["home-care agency placement and care-management services"],"free_alternatives":["AARP hiring guidance and checklist","personal spreadsheet or notes"],"specific_advantage":"Works against actual proposals and preserves what each agency said; it does not repeat a generic hiring checklist.","reachable_channel":"Amazon exact-query shelf plus caregiver-resource search; employer caregiver programs are a possible later channel, not assumed.","main_unverified_assumption":"Families will pay for proposal normalization rather than use the free checklist.","cheapest_test":{"not_authorized":"One-page offer and four-page non-medical comparison packet shown to 8–12 people currently comparing agencies; ask for a real $12 purchase of the finished packet, with no preorder.","signals":"Record view, comprehension, purchase attempt and completed payment separately."},"continue_if":"At least 2 completed payments from 10 qualified current buyers and no recurring demand for medical/legal guidance.","reject_if":"No completed payment after 10 qualified exposures, or buyers primarily want individualized care/legal advice.","anton_involvement":"About 30 minutes to approve test packaging; no subject-matter judgment."},
      {"opportunity_id":"RN7R-006","status":"INSUFFICIENT_EVIDENCE","buyer_and_moment":"Homeowner holding a professional energy-audit report before requesting retrofit quotes.","promised_result":"Turn recommendations into staged quote requests, assumptions and a decision record.","content_and_format":"Paperback reference and write-in action packet; no engineering or savings guarantee.","price_hypothesis":{"value_usd":14.99,"confidence":"LOW","basis":"Visible adjacent home-energy paperbacks cluster roughly around EUR8–21, but report-decoder demand is unobserved."},"paid_alternatives":["energy auditor follow-up","contractor consultation"],"free_alternatives":["DOE guide","auditor report","spreadsheets"],"specific_advantage":"Post-audit coordination across competing retrofit quotes rather than DIY auditing.","reachable_channel":"Amazon home-energy-audit queries.","main_unverified_assumption":"Post-audit homeowners seek a book-shaped coordination tool.","cheapest_test":{"not_authorized":"Keyword-specific offer test against a four-page report-to-quote packet with 10 recent audit buyers; require completed payment, not stated interest.","signals":"Track view, click, request and completed payment separately."},"continue_if":"At least 2 completed payments from 10 qualified recent-audit homeowners.","reject_if":"No payments or buyers expect engineering/savings advice.","anton_involvement":"About 30 minutes to approve test packaging."}
    ]
    status_counts={state:sum(x["decision_state"]==state for x in s) for state in ["REJECTED_ON_EVIDENCE","INSUFFICIENT_EVIDENCE","ATTRACTIVE_BUT_NOT_FOR_US","READY_FOR_VALIDATION"]}
    dump("buyer-situations.json",{"schema_version":"book-radar-buyer-situations/v1","run_id":"RN7-PAID-NEED","strategy":"candidate-generation-v3-paid-need","observed_at":DATE,"count":len(s),"situations":s})
    dump("evidence-ledger.json",{"schema_version":"book-radar-evidence-ledger/v2","run_id":"RN7-PAID-NEED","sources":SOURCES,"rules":{"sales_not_invented":True,"single_bsr_not_sales_estimate":True,"same_publisher_pages_count_once":True}})
    dump("deep-checks.json",{"schema_version":"book-radar-deep-checks/v1","count":len(deep),"candidates":deep})
    dump("commercial-hypotheses.json",{"schema_version":"book-radar-commercial-hypotheses/v1","count":len(hypotheses),"production_authorized":False,"external_tests_launched":False,"hypotheses":hypotheses})
    weights={"buyer":15,"jtbd":25,"trigger":10,"promise":20,"format":5,"information_architecture":10,"search_intent":5,"audience":5,"differentiation":5}
    facets={"buyer":20,"jtbd":20,"trigger":15,"promise":25,"format":75,"information_architecture":75,"search_intent":15,"audience":20,"differentiation":30}
    similarity=assess_portfolio_similarity(facets,weights)
    dump("retained-gates.json",{"schema_version":"book-radar-retained-gates/v1","opportunity_id":"RN7R-009","rights":{"status":"PASS","basis":"Original comparison forms; external guidance paraphrased and cited."},"language":{"status":"PASS","basis":"English is supported; no bilingual dependency."},"format":{"status":"PASS","basis":"Paperback reference/workbook is KDP-compatible; no final files created."},"factual_reliability":{"status":"PASS_WITH_REFRESH","basis":"Current AARP and source-ledger claims; state-specific employment and medical advice excluded."},"portfolio_similarity":{"status":"PASS","catalog_checked":"persistent portfolio catalog plus known production architectures","matched_product":"THE HUMAN BACKUP PLAN","architecture_warning":"RN5-001 uses a similar proposals-to-decision mechanism, but serves a different buyer, trigger and promise.","facets":facets,"weights":weights,**similarity},"anton_attention":{"status":"PASS","validation_hours_estimate":0.5},"production_authorized":False})
    comparison={"RN6":{"situations":330,"spending_evidence_share":"NOT_RECORDED","book_format_evidence_share":"NOT_RECORDED","late_gate_failures":10},"RN7_paid_need":{"situations":len(s),"deep_checks":len(deep),"spending_evidence_supported_share":round(sum(x["evidence_dimensions"]["spending_evidence"]["status"]=="SUPPORTED" for x in s)/len(s),3),"book_format_supported_share":round(sum(x["evidence_dimensions"]["book_format_demand"]["status"]=="SUPPORTED" for x in s)/len(s),3),"states":status_counts,"research_cost_proxy":{"sources":len(SOURCES),"sources_per_supported_validation_hypothesis":len(SOURCES)}},"interpretation":"RN7 detects several late-stage RN6-style failures at broad/deep screening, but different sample construction and missing RN6 fields prevent a causal or statistical improvement claim.","source_utility":{"books_and_materials":"Best at proving book-format behavior and exposing direct competitors; weak at proving the underlying job alone.","service_or_training_spend":"Best at proving consequential spending and trigger; does not prove book demand.","unmet_need_sources":"Useful for generating situations; weakest for willingness-to-pay without independent spending and format evidence."}}
    dump("rn6-comparison.json",comparison)
    report=f"""# RN7 paid-need recalibration\n\n## Decision\n\n**READY FOR VALIDATION — not production.** One of 12 buyer situations has enough independent problem, spending, adjacent book-format, gap, reachability and delivery evidence to justify a paid-intent test: **RN7R-009, In-home Caregiver Agency Proposal Comparator**. RN7R-006 remains an explicitly insufficient-evidence backup.\n\nThe original 360-item RN7 run is preserved. This bounded rerun uses a new immutable ID (`RN7-PAID-NEED`) because its search unit and evidence rules differ materially. RN6 remains `NO_PRODUCT`.\n\n## Funnel\n\n- Buyer situations: 12\n- Deep checks: 5\n- Commercial hypotheses retained: 2 (one ready, one insufficient)\n- States: {status_counts}\n- Production authorized: no\n\n## Why RN7R-009 survives\n\nAARP independently establishes a real family decision and existing paid home-care use. Amazon shows paid caregiver books/workbooks are natural, while the exact agency-comparison query exposes only one old direct guide. The proposed advantage is narrow: normalize actual agency proposals and preserve written answers. The remaining question is willingness to pay; no sales estimate is invented.\n\n## Stop rule\n\nThe bounded pass stopped after five deep checks. More search was unlikely to change the controlling unknown: whether qualified buyers will pay for proposal normalization. The next step is a separately authorized, payment-observing test. No manuscript, sample, listing, landing page, advertisement or contact was created.\n"""
    (OUT/"radar-native-7-paid-need-report.md").write_text(report)
    learning="""# RN7 paid-need learning\n\nStarting from paid situations changed the failure timing. RV, HOA, septic and financial-aid concepts were rejected before product work because current books or free tools already capture the proposed outcome. Horse, tree-risk, food-truck, marine and art candidates were separated as `ATTRACTIVE_BUT_NOT_FOR_US` instead of being mislabeled as no demand.\n\nAmazon/book discovery was most useful for format evidence and competitive falsification. Service-spend discovery was most useful for proving the problem and buyer value, but regularly failed to prove book demand. Unmet-need discovery produced useful prompts but the weakest commercial proof.\n\nOne ready-for-validation hypothesis is not evidence that the new method outperforms RN6. RN6 did not store comparable spending and format fields, and sample sizes differ. Keep the strategy experimental until multiple out-of-sample runs or paid tests produce comparable outcomes.\n"""
    (OUT/"radar-native-7-paid-need-learning.md").write_text(learning)
    bundle={"schema_version":"book-radar-import/v1","radar_runs":[{"id":"RN7-PAID-NEED","name":"RN7 paid-need recalibration","observed_at":DATE,"status":"READY_FOR_VALIDATION","strategy":"candidate-generation-v3-paid-need","production_authorized":False}],"opportunities":[{"id":x["id"],"radar_run_id":"RN7-PAID-NEED","buyer_job":x["job_to_be_done"],"query_cluster":x["discovery_channel"],"format":x["publishing_format_fit"],"price_band":"UNVALIDATED","concept":x["name"],"buyer_situation":{k:x[k] for k in ["buyer","payer","purchase_trigger","deadline","current_solution","current_spend","unmet_need"]},"evidence_dimensions":x["evidence_dimensions"]} for x in s],"evidence":[{"id":f"evidence:{x['id']}:paid-need","opportunity_id":x["id"],"observed_at":DATE,"summary":x["decision_reason"],"details":{"evidence_dimensions":x["evidence_dimensions"],"source_ledger":"book-radar/runs/rn7-paid-need/evidence-ledger.json"},"source_ref":"book-radar/runs/rn7-paid-need/buyer-situations.json"} for x in s],"decisions":[{"id":f"decision:{x['id']}:paid-need","opportunity_id":x["id"],"decision":x["decision_state"],"reason":x["decision_reason"],"decided_at":DATE,"production_authorized":False} for x in s],"similarity_results":[{"id":"similarity:RN7R-009:B0HFTTG5FH","opportunity_id":"RN7R-009","portfolio_product_id":"portfolio-product:B0HFTTG5FH","facets":facets,"weights":weights,**similarity}]}
    dump("book-radar-import.json",bundle)
    print(json.dumps({"situations":len(s),"deep":len(deep),"hypotheses":len(hypotheses),"states":status_counts},indent=2))


if __name__ == "__main__":
    main()
